language: python
python: "3.6"

cache: pip

install:
  - pip install -r requirements.txt

addons:
  sonarcloud:
    organization: "ronek22-github"

script:
  - pytest --cov-config .coveragerc --cov-report xml:coverage.xml --cov=running_calculator tests/
  - pytest --cov-config .coveragerc --cov=running_calculator tests/
  - sonar-scanner

after_success:
  - codecov
