language: python
python: "3.6"

install:
  - pip install -r requirements.txt

addons:
  sonarcloud:
    organization: "ronek22-github"

 
script:
  - pytest --cov=runningCalculator tests/
  - sonar-scanner
